
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-elasticsearch
spec:
  template:
    spec:
      containers:
        - name: wazuh-elasticsearch
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: wazuh-elasticsearch
        namespace: es-cluster
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2-encrypted-retained
        resources:
          requests:
            storage: 10Gi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  template:
    spec:
      containers:
        - name: wazuh-kibana
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 2Gi
